production.h File Reference
Functions
bool production (int argc, char *argv[])
void PlayOne (unsigned int nr, unsigned int nc, char *Old, char *New)
void printBoard (int nc, int nr, char *p)
int doGenerations (unsigned int nr, unsigned int nc, int given_gens, char *A, char *B, char *C, char print, char pause)
bool checkArrayEquals (int nc, int nr, char *A, char *B)
int CountNeighbors (unsigned int r, unsigned int c, int nRows, int nCols, char *Old)
Function Documentation
checkArrayEquals()
bool checkArrayEquals (int nc, int nr, char * A, char * B)
Checks to see if the arrays are equal.
Parameters
nr The rows of the playing field.
nc The columns of the playing field.
A The character pointer to the first array, A, being compared.
B The character pointer to the second array, B, being compared.
Returns
areEqual true if all the characters in the array are the same, false if any of the characters in the array are different.
Referenced by doGenerations(), and testCheckArrayEquals().
CountNeighbors()
int CountNeighbors (unsigned int r, unsigned int c, int nRows, int nCols, char * Old)
Function that counts the neighbors, on all eight sides, of the cell being examined.
Parameters
r Row coordinate of cell.
c Column coordinate of cell.
nRows The rows of the playing field.
nCols The columns of the Playing field.
Returns
occupied The number of occupied neighbors.
Referenced by PlayOne(), and testCountNeighbors().
doGenerations()
int doGenerations (unsigned int nr, unsigned int nc, int given_gens, char * A, char * B, char * C, char print, char pause)
Calls PlayOne for the input amount of generations given, unless 1) All organisms die. 2) The pattern of organisms from the previous generation repeats itself. 3) The predefined number of given generations is reached.
Parameters
nr Row coordinate of cell
nc Column coordinate of cell
A The character pointer to the (Old) array, A.
B The character pointer to the (New) array, B.
C The character pointer to the (Other, grandfather) array, C.
print An optional argument with the value of 'y' or 'n' indicating whether a each generation (including generation 0), should be displayed or printed before proceeding to the next generation.
pause An optional argument with the value of 'y' or 'n' indicating whether a keystroke is needed between generations. Defaults to 'n'.
Returns
occupied The number of occupied neighbors.
References checkArrayEquals(), PlayOne(), and printBoard().
Referenced by production(), and testDoGenerations().
PlayOne()
void PlayOne (unsigned int nr, unsigned int nc, char * Old, char * New)
Plays the game of life: If an occupied cell, 'x', has less than 2, or greater than 3 neighbors, the organism and becomes an, 'o'. If an occupied cell, 'x' has 2 or 3 neighbors, the organism survives to the next generation. If an unoccupied cell, 'o', has precisely 3 occupied neighbors, it becomes occupied by a new organism, 'x'.
Parameters
nr The rows of the playing field.
nc The columns of the playing field.
Old The character pointer to the Old array.
New The character pointer to the new array.
References CountNeighbors().
Referenced by doGenerations(), and testPlayOne().
printBoard()
void printBoard (int nRows, int nCols, char * L)
Prints out the board.
Parameters
nRows The rows of the playing field.
nCols The columns of the Playing field.
Referenced by doGenerations(), and testPlayOne().
production()
bool production (int argc, char * argv[])
Your production code goes in this function.
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line.
Returns
true if Program was able to play the game of life false if User entered bad input.
References doGenerations().
Referenced by main().