tests.c File Reference
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
bool tests (void)
bool testReadInput (void)
bool testMakeArrays (void)
bool testPlayOne (void)
bool testCountNeighbors (void)
bool testCheckArrayEquals (void)
bool testDoGenerations (void)
Function Documentation
testCheckArrayEquals()
bool testCheckArrayEquals (void)
This function calls checkArrayEquals and checks to see if the given arrays are the same.
Returns
true if the given arrays are equal. false if the any of the elements in the arrays are different.
References checkArrayEquals().
Referenced by tests().
testCountNeighbors()
bool testCountNeighbors (void)
This function calls CountNeighbors and checks to see if it counting the right amount of neighbors.
Returns
true if the correct neighbors are counted for a certain cell. false if the neighbors counted are incorrect.
References CountNeighbors().
Referenced by tests().
testDoGenerations()
bool testDoGenerations (void)
This function calls doGenerations and checks to see if doGenerations quits when it is supposed to.
Returns
true if doGenerations returns the correct count of generations. false if doGenerations returns the incorrect count of generations.
References doGenerations().
Referenced by tests().
testMakeArrays()
bool testMakeArrays (void)
This function checks to see if the arrays are able to be made properly.
Returns
true if Program was able to create arrays. false if the arrays are not able to be made.
Referenced by tests().
testPlayOne()
bool testPlayOne (void)
This function calls PlayOne and checks to see if it is working properly.
Returns
true if PlayOne does what it is supposed to do. false if PlayOne does not work properly.
References PlayOne(), and printBoard().
Referenced by tests().
testReadInput()
bool testReadInput (void)
This function checks to see if the file input is being read properly.
Returns
true if the file input was read properly. false if file input was not able to be read.
Referenced by tests().
tests()
bool tests (void)
This function calls all the test functions and checks to see if everything is working properly.
Returns
true if Program was able to play the game of life false if something went wrong in the tests.
References testCheckArrayEquals(), testCountNeighbors(), testDoGenerations(), testMakeArrays(), testPlayOne(), and testReadInput().
Referenced by main().